### ISSUE TITLE
Recover Documentation steps that Jesse Smith started

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-data#12]
At the onset of this project, Jesse did some work collecting the source material used for the creation of the data in the CalVIN model. That was pre-github, and we need to rethink how that would go into the repo.  We also need to capture his work and get the sources in here as well.  Finally, Jesse did some scripting in creating a Mendeley account that includes all this data.  Looking through this, I'm not convinced it's the best method, because: 
- I can't convince Mendeley to make those documents available to the public at large
- The document list look pretty bad without title, authors, etc.

However, I think you can download a standard JSON version of the citation info, which we might want to use ourselves?

**Comment by jrmerz** [comment]
Can you share the mendeley account with me and/or give me a pointer?

**Comment by qjhart** [comment]
Have done, and sent along Jesses list of found sources.

**Comment by jrmerz** [comment]
(side note, just sent forwarded email with new subject 'for calvin-network-data issue #12' ... gmail needs to add github issue tagging ... )

**Comment by qjhart** [comment]
@jrmerz regarding this, can we reassociate the original source material to the id numbers in the database?

**Comment by jrmerz** [comment]
@qjhart which database on which server?  Also, which server is the spreadsheet referencing when it says 'Hobbes'?

**Comment by qjhart** [comment]
This data has been recovered, and uploaded into sources at: f263486
