### ISSUE TITLE
Updated format for CSV files

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-data#2]
I think all CSV files should be only for one type, and not for multiple names in the same file.  This should make for more simple ingests.  Although there wil be multiple files for arrays of data.  Also, I think the json-schema should be modified to eliminate the object names for arrays of data.  For example, for inflows; the new schema (see https://github.com/ucd-cws/calvin-network-data/blob/master/json-schema/inflow.json), defines an inflow as either null; a pointer to an external file; or an array of array values.  That means that in a json file that included the data, the data would look like:

```
inflows:['identifier',[['2014-10-01',23.4],['2014-11-01',50]...]]
             'id2',[['2014-10-01',5.4],['2014-11-01',1.2].....]
            ]
```

The point being that anything that is represented as CSV file potentially, is _always_ an array of array values, with the obvious translation to the CSV format.

**Comment by qjhart** [comment]
Checkout the _csv_update_ branch for an example.

**Comment by jrmerz** [comment]
@qjhart In your example, why is the 'inflows' value an array and not an object?  

```
inflows : { 
  'identifier' : [['2014-10-01',23.4],['2014-11-01',50]...]]
  'id2'        : [['2014-10-01',5.4],['2014-11-01',1.2].....]
}
```

translating to

```
inflows : { 
  'identifier' : {'$ref' : 'inflows_identifier.csv'}
  'id2'        : {'$ref' : 'inflows_id2.csv'}
}
```

**Comment by qjhart** [comment]
Yeah, that is better. I wonder if I can create a json-schema definition to match that.

**Comment by qjhart** [comment]
Yes, that can be done.  I am struggling with the notion of identifiers.  In one sense, they are nice to have; but are they required?

```
inflows : [ [['2014-10-01',23.4],['2014-11-01',50]...], {"$ref" : 'inflows_id2.csv}]
```

On the other hand, should they be expanded?

```
inflows : { 
  'identifier' : {description:'This is where we put info.", data: {'$ref' : 'inflows_identifier.csv'}},
  'id2'        : {'$ref' : 'inflows_id2.csv'}
}
```

You can actually see this in the original inflow data. I'm not super excited about all the _data:_ references.

**Comment by jrmerz** [comment]
@qjhart why not...

```
inflows : { 
  'identifier' : {
     description : 'This is where we put info.",
     '$ref'      : 'inflows_identifier.csv'
  },
  'id2'        : {'$ref' : 'inflows_id2.csv'}
}
```

?

**Comment by qjhart** [comment]
Because then the location of the data in a complete record would be different. 
You would have to have:

```
inflows : { 
  'identifier' : {
     description : 'This is where we put info.",
     'citition' : {'$ref' : 'Justin was right :)' },
     '$ref'      : 'inflows_identifier.csv'

  },
  'id2' : {
     description : 'This is where we put info.",
     'data'      : [['2014-10-01',23.4],['2014-11-01',50]...]
  },
```

On the plus, lets throw in `citation` and you have now convinced me your idea was better :)

**Comment by jrmerz** [comment]
Ok, sounds good :+1:
