### ISSUE TITLE
Create a DSS exporter for the network model runs

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-data#21]
We need to use the DSSVUE software to export the network model into a DSS format to be ready for import into the network model.  Since this is a java program, I think this would be best to have a standalone interface.  Something, like where you would identify a list of filenames and paths, and the script would create a single DSS files with all those links included.   I don't recall how the DSS importer works, we may have to create templates for the different types of CSV files as well.

**Comment by jrmerz** [comment]
Clarification:  "DSSVUE software to **export the network model** into a DSS format to be ready for **import into the network model**". 

What is the data flow?

**Comment by qjhart** [comment]
With cf192a2 I have added the DSS export utility. The way that the calvindb project builds this new database with the the dss2csv script. This is a batch script working on the DSSVUE java software. This script exports every DSS item into a row of a CSV file. In this case the array data is exported as a postgres object, but it could just as easily be a JSON object as well. I expect the Import step to be similar. Either we have a prestep to compute a complete CSV file in a similar manner, or we have a file with a list of DSS locations, and filenames, and we fetch the CSV files from the filesystem.

**Comment by qjhart** [comment]
@terencewu  I've tried to get the start of an export to dss script in place.  I found that the distributed version of jython is too old for the `csv` module of python.  I've updated this as described in #25.

**Comment by jrmerz** [comment]
Believe this is implemented by: https://github.com/ucd-cws/calvin-network-tools
