### ISSUE TITLE
Just use index.geojson for nodes, links and regions

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-data#28]
Not sure we gain any benefit from having these named different things.  I guess we don't have to parse JSON, but think maybe a common method is better.

**Comment by jrmerz** [comment]
I'm ok with renaming [node|link].geojson.  The regions importer however uses that inheritance model I talked about, which can be done with the region files named index.json, but then every json file needs to be parsed first to inspect if it is a region or not.  Do you still want to proceed?
