### ISSUE TITLE
Shorthand node and Link names

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-data#29]
I've discussed the need for relative paths, but there is this problem of making the names short but globally ok for both the PRI file, and the links in the db.  Here is one idea:

```
ea_eastside/ # shorthand ea
                   foo # global ea.foo
sc_sacramento_river/  # global sc
                                  foo
                                  bar
                                  foo-bar # relative link
                                  yb_yuba_city_urban_demand/
                                                                                  wtp # yb.wtp and sc.yb.wtp both work
ea.foo-yb.wtp  # global links
```

Then in PRI file we use `ea.foo, sc.foo sc.bar yb.wtb`

**Comment by jrmerz** [comment]
Need more info.  Perhaps a cleanup of the code snippet?

**Comment by qjhart** [comment]
We discussed this as at the 2015-08-25 meeting.  I have started a small application that shows the smallest shorthand for each link.  Still needs to be worked out.
