### ISSUE TITLE
Get a List of all the Post-Processes that are required from the data.

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-data#30]
Right now we are focusing on the scarcity postprocessing.  We need to get the list of post-processing steps that Josue acquired for a more complete set.

**Comment by qjhart** [comment]
@josue-medellin you  can just add the list, and desciptions (if you have them) directly to this issue.

**Comment by josue-medellin** [comment]
Quinn, should I add a text file with the steps to follow postprocessing of scarcity?

**Comment by qjhart** [comment]
@josue-medellin That one is documented at: https://github.com/ucd-cws/ca-water-network/issues/4 since i think we can do it all with the data we have.  You can add to that issue, if you think something is missing.  We need to think about any other post-processing.

**Comment by qjhart** [comment]
There should be three post-processing events.  @jrmerz THis is is probably in the browser tool.
