### ISSUE TITLE
Complete the geolocation part of the node/link inspector tool

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-data#34]
There is the beginnings of a node/link inspection tool, https://github.com/ucd-cws/calvin-network-data/blob/master/bin/inspect/index.js . This is maybe misnamed as I'd like some editing capability to that as well.  One feature should be the ability to edit the location of a node from the command line, maybe with something like 

``` bash
cwn-inspect  --edit --ll=38.123,-121.456 --reverse  sr_sacramento_river/u202 
```

Where the appropriate geojson file is found, and the centroid is modified accordingly.

**Comment by qjhart** [comment]
``` bash
node cmd -m node -f edit_location sr_sac/u202 38.123,-121.456 reverse
```

But maybe 

``` bash
node cmd -m node -f edit_properties sr_sac/u202 {description:"This is new"}
```

``` bash
node cmd -m network -f dump_location
```

| filename | id | longitude | latitude |
| --- | --- | --- | --- |

**Comment by jrmerz** [comment]
Added to master of app repo.  Functions are documented here: https://github.com/ucd-cws/ca-water-network/tree/master/lib/cmd
