### ISSUE TITLE
Metadata Standards

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-data#36]
There is interest in capturing the metadata records that have previously been entered.  The previous metadata is pretty complicated.   You have the ability to assigin a metadata record to a large number of things.  

| item | count |
| --- | --- |
| Inflows.Inflow | 51 |
| Link.Amplitude | 136 |
| Link.Cost | 86 |
| Link.LowerBound | 42 |
| Link.LowerBoundMonthly | 5 |
| Link.LowerBoundPathname | 32 |
| Link.UpperBound | 112 |
| Link.UpperBoundMonthly | 141 |
| Link.UpperBoundPathname | 20 |
| Nodes.AreaCapFactor | 37 |
| Nodes.ElevationArearCapacityPathname | 37 |
| Nodes.EndingStorage | 31 |
| Nodes.EvaporationRatePathname | 38 |
| Nodes.InitialStorage | 51 |
| PenaltySets.PenaltySet | 31 |

My simple proposal is to allow users to put README.md files anywhere in the database.  These  do not have to be referenced by any of the geojson files.  If they exist in a node/link/region directory, they are added directly as a `README` property.  

In addition, you have the option of explicitly pointing to a `*.md` file from any other object within the JSON file.  For example, if you have data like this: 

``` json
{"type":"Feature",
 "geometry":null,
 "properties":{"prmname":"U502-INT AV",
 "description":"Total Urban Penatly Function",
 "type":"Diversion",
 "origin":"U502",
 "terminus":"INT AV",
 "amplitude":1,
 "costs":{ "type":"Monthly Variable","costs":{"JAN":{"$ref":"costs/JAN.csv"},"FEB":{"$ref":"costs/FEB.csv"},"MAR":{"$ref":"costs/MAR.csv"},"APR":{"$ref":"costs/APR.csv"},"MAY":{"$ref":"costs/MAY.csv"},"JUN":{"$ref":"costs/JUN.csv"},"JUL":{"$ref":"costs/JUL.csv"},"AUG":{"$ref":"costs/AUG.csv"},"SEP":{"$ref":"costs/SEP.csv"},"OCT":{"$ref":"costs/OCT.csv"},"NOV":{"$ref":"costs/NOV.csv"},"DEC":{"$ref":"costs/DEC.csv"}}},
 "bounds":[{"type":"UBT","bound": {"$ref":"./UBT.csv"}}],
 "sinks":null,
 "flow":null}}
```

You could rewrite as: 

``` json
{"type":"Feature",
 "geometry":null,
 "properties":{"prmname":"U502-INT AV",
 "description":"Total Urban Penatly Function",
 "type":"Diversion",
 "origin":"U502",
 "terminus":"INT AV",
 "amplitude":1,
 "costs":{ "type":"Monthly Variable", "README":"costs/README.md",
 "costs":{"JAN":{"$ref":"costs/JAN.csv"},"FEB":{"$ref":"costs/FEB.csv"},"MAR":{"$ref":"costs/MAR.csv"},"APR":{"$ref":"costs/APR.csv"},"MAY":{"$ref":"costs/MAY.csv"},"JUN":{"$ref":"costs/JUN.csv"},"JUL":{"$ref":"costs/JUL.csv"},"AUG":{"$ref":"costs/AUG.csv"},"SEP":{"$ref":"costs/SEP.csv"},"OCT":{"$ref":"costs/OCT.csv"},"NOV":{"$ref":"costs/NOV.csv"},"DEC":{"$ref":"costs/DEC.csv"}}},
 "bounds":[{"type":"UBT","README":"UBT.md","bound": {"$ref":"./UBT.csv"}}],
 "sinks":null,
 "flow":null}}
```

Which would include two other README files.  `costs/README.md` and `UBT.md`.   I can't think of a better method to join multiple files.

**Comment by qjhart** [comment]
Alternatively, we can only have one README file, and then divide the README into pieces using headers.  Then if the header has a mongodb filter/projection that looks valid, the comment is for that particular component.  Actually, I like this better.  First, you can read all the comments in one place, second, we can defer putting access to the metadata in multiple places for awhile, but get there eventually.  Third only one place for README editing.

``` md
## <qjhart@ucdavis.edu> 2015-04-01 [{bounds:1}]
Performed magic on the Upper bounds.
```

**Comment by qjhart** [comment]
@jrmerz What do you think re. either of these strategies?

**Comment by qjhart** [comment]
## 2015-05-09 Quinn Hart qjhart@ucdavis.edu {amplitude:1}

Below this, you should have, in reverse chronological order, the changes that have been made to this.  The headline should include the date, and the author, and optionally, the part of the data that you are working on.  This can be explained in this section as well.

## 2015-05-18 Quinn Hart qjhart@ucdavis.edu {bounds:1}

You have three options of identifing supporting documentation.  If this data comes from a published document, then you should reference the publication.  For this we encourage the use of [Mendelay](http://mendelay.com), [Research Gate](http://researchgate.com) or another online citation tool.  You should link to that publication, but also include a citation in the comments, as below:

A second option, if this is based on internal work, is to include your work in UC's scholar share website. This allows you to upload a research document, and publish there.  It is useful for non-peer reviewed documents.  Here

As a final option, you can include supporting materials in this repository, under the `/sources` directory.  Please make a new directory for any new source.  That is identitifed with an absolute path to the data as in:
- [Spreadsheet](https://github.com/ucd-cws/calvin-network-data/blob/master/sources/calvin001/main.dat) - Includes the calculations used to derive....

**Comment by jrmerz** [comment]
App now imports and renders README.md markdown ucd-cws/calvin-network-app@69b29dce09b57c3798ff300a55b7f55bc7220a75

**Comment by qjhart** [comment]
Starting with 7f5fb05300c7a6d9963c0b51626f91f5510c399d we have READMEs.  They need to be reviewed, and more importantly, they need to have the information to their supporting data included.
