### ISSUE TITLE
c87 _ d76a _d77

### ISSUE THREAD

**Issue by mclay120** [ucd-cws/calvin-network-data#39]
Description suggests it should be in the order C87_D77_D76a.
Search for Ord Ferry Reach (D76a) is in Chico, downstream from D77 (Red Bluff diversion dam).

**Comment by qjhart** [comment]
@msdogan can you look at this small section, and see about the order of these nodes?

**Comment by msdogan** [comment]
Looks like D76a is a dummy node. Probably there was a minimum in-stream flow requirement downstream of that node but got rid of / displaced it. If you like I can take d76a out in the next version. Or we can update the description.

**Comment by qjhart** [comment]
@msdogan .  Let's remove it on next version. Do you think we will have another import of a new database? Or will this be done in the Hobbes method?

**Comment by msdogan** [comment]
What I am going to do is to go to link C87_D76a and change destination node from D76a to D77. And then remove Node D76a. We can try in the Hobbes as well but I need your help to do so.
