### ISSUE TITLE
Nodes prmnames should not have '-' in them

### ISSUE THREAD

**Issue by jrmerz** [ucd-cws/calvin-network-data#43]
I thought we had discussed only allowing link prmnames to have '-'.  That way they were always [prmname_origin]-[prmname_terminus].  If we allow '-' in node names as well you can't infer if it's a node or link from the name.  Let me know if I am wrong on this.

**Comment by qjhart** [comment]
This is a non-resolved issue.  Currently, I have not made changes to the prmnames from the input system, only to the filename of the nodes.  I realize this is not ideal.  I'll send a note about this to all.  However the node type can be used as well.

**Comment by jrmerz** [comment]
The problem is with the new 'Region Link' type.  You can think of them as virtual links.  I want to keep the url structure the same in the application, so the url for a region link is /#info/[region/node origin]-[region/node terminus].

When the info page loads, it attempts to lookup the node by the defined url parameter (prmname).  If the given prmname can't be found, the app assumes the prmname is for a Region Link.  The app splits on '-' to lookup the origin and terminus from either the region list or the node list.  Then renders.   When node names have '-' in them, this split does not produce the correct origin and prmnames.

The workaround is to add a new character to the prmname for this one purpose, indicating a Region link and allowing determined splitting of the name to figure out it's region/node components.  I would rather just use the '-' as I thought that was it's purpose.

**Comment by jrmerz** [comment]
temp fix here for now ucd-cws/calvin-network-app@76638d4511a30af4fbf40dcff4c57429456be782

**Comment by qjhart** [comment]
@josue-medellin / @msdogan  We have visited this before, but this is another change.  When going to the new fs based version we propose to elminate all but [a-z][0-9]_ from node names.  This is primarily to match using '-' for links only, and to elminate spaces and ':'.  This does not lead to any name collisions.  We also like to switch to lowercase, but that's just for easier typing.  Comment if you have any problems with these changes.

Below are some example changes.

| old | new |
| --- | --- |
| agg av | agg_av |
| ags: bard | ags_bard |
| eres cc | eres_cc |
| eres: cmwd | eres_cmwd |
| ext av | ext_av |
| gw-vc | gw_vc |
| hsu202sr-6 | hsu202sr_6 |
| ind ccwd | ind_ccwd |
| ind: cmwd | ind_cmwd |
| pmp-badger | pmp_badger |
| r-sut | r_sut |
| sr-ber | sr_ber |
| surp delta | surp_delta |

**Comment by msdogan** [comment]
I think we have discussed this before that we would use "-" only for links and for the rest such as space, we would use "_" but we never applied that change. I can make those changes.

**Comment by msdogan** [comment]
One more thing. There is a limit in PRM names for nodes that they cannot exceed 10 character. But there is no limit on node labels, so sometimes you see that prmnames are shorter than node labels. For example, this is node label HSU409BD862B, and prm name HSU409BD86, which is missing "2B" at the end. Hope this does not create so much trouble.
