### ISSUE TITLE
Missing Sink on 'D94' - Other Bad Bounds

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-data#48]
@msdogan, we discussed that fact that node D94 was missing a sink.  I tracked that down, to a quick fix that I made, where I eliminated some Sinks from the network where the LowerBoundPathname was  not in the TS.dss file.  This included the `D94` sink.  Either that was a mistake or it was fixed on an updated version.  There is still one item however where the LowerBoundPathname for a link is not in the TS.DSS file, I beleive.

| ID | Name | Description | LowerBoundPathname |
| --- | --- | --- | --- |
| 711 | C54_D608 | St.James and N.Kings River outflow from Region 4 to Region 3.  This is not the depletion to the Fresno Slough. | /UCD CAP1/C54_SINK/FLOW_FXC(KAF)//1MON/BOUNDARY FLOW 3 WITH LOSSES/ |

**Comment by msdogan** [comment]
Yes, it's good that you have eliminated pathnames that are not in the TS.dss or PD.dss files. However, for D94 we have time-series in TS.dss file with a pathname "/HEXT2014/D94_SINK D94/FLOW_LBT(KAF)//1MON/CALSIM - C100_MIF/". For the link C54_D608 yes, we don't use "/UCD CAP1/C54_SINK/FLOW_FXC(KAF)//1MON/BOUNDARY FLOW 3 WITH LOSSES/" instead flows on this link is constrained and pathname is "/HEXT2014/C54_D608/FLOW_EQC(KAF)//1MON/CALSIM I607/"

**Comment by qjhart** [comment]
Yes, all accounted for, the import uses the EQC, but still gets a little confused with the LB.
