### ISSUE TITLE
Updates to the dssWriter - Command Line and new writers.

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-data#50]
Updates are required to use the prm builder.
I have added some pseudo code at 6d3cab95f37cbf3091e32dfd627dfd1ba630d002 that shows the three types of dss inputs, and how we need to modify the command line parameters to support the different types of data that go into the DSS files. It's on a separate branch, since it's not even good comments.

**Comment by jrmerz** [comment]
Why are you moving logic to the jar?  I like the idea of just passing what you think each part (A-E) should be.  But why add a path parameter that the java code needs to parse?  Seems like you are proposing more functionality when we had discussed the java code doing as little as possible.

**Comment by qjhart** [comment]
I basically left that in since it was there already, but I don't see why we would ever use it, so we can leave  that out.  It's not really really moving logic into  there however, just giving us the abilitiy to add in non-standard entries to a DSS file if ever needed.   The part[] spec is HEC-PRM specific.

**Comment by qjhart** [comment]
Also, Although my notes are conflicting, I think we should use partD as Q(KAF)-P_EDT and PS_EDT since I think they are correct.

**Comment by jrmerz** [comment]
So I have added the Jackson library, which gives us json parsing.  The current code (just checked in above) has the idea that there is almost a one-to-one correspondence between a passed JSON object and what is written in java.  There will only be one input parameter as well, a giant JSON string.

so it will be run like

```
[wine] java -Djava.library.path="../../lib;${env_var:PATH}" -jar ../../dssWriter.jar [json]
```

what json looks like

```
{
  "path" : "/path/to/dss/file",
  "data" : [{
     "type" : "paired", // can be 'paired' or 'timeseries', tells java lib which container to create
     "csvFilePath" : "/path/to/csv/file/to/read",
     "label" : "a label",
     "path" : "/dss/entry/path/name",
    // again, you will be able to set parameters of containers.  almost one-to-one mapping 
 }, ...]
}
```

Under this setup you will also be able to supply as many writes as you would like per call to the jar.

**Comment by qjhart** [comment]
Is this in addition, or as an alternative?  I still like the idea of
java dssWriter --partB=Foo --partD='K(KAF)-EDT' --partE='APR'
--csv=./.../APR.csv

**Comment by jrmerz** [comment]
Why?  This library should only be used wrapped in our NodeJS code.  This is
what we discussed, no?

Creating the 'node prm' interface that follows this convention would be fine.  But under the hood, the communication with java would always be this JSON object.

**Comment by jrmerz** [comment]
The NodeJS code and Java code have been updated to use JSON as the communication protocol.  The command line 'API' and/or flags should be defined/parsed in NodeJS then sent as this standard JSON packet to the Java code.  Currently the cost paired data write example using the output, csv, month and prmname flags can be seen [here](https://github.com/ucd-cws/calvin-network-data/blob/add-dss/export/nodejs/prm/cmds/build.js#L21).

@qjhart does this sound ok?

PS the HEC_Runtime alpha 1 release has been switched to this new strategy.

**Comment by qjhart** [comment]
@jrmerz. Yep, sounds good.

**Comment by jrmerz** [comment]
Ok with this issue implemented.  Let's keep the rest of the command line tools discussion happening on issue #27
