### ISSUE TITLE
Negative evaporation data

### ISSUE THREAD

**Issue by jrmerz** [ucd-cws/calvin-network-data#53]
@qjhart some of the evaporation data is negative?  Is that correct?  Ex:
https://github.com/ucd-cws/calvin-network-data/blob/master/data/sacramento-river/southeast/sr_oro/evaporation.csv

**Comment by msdogan** [comment]
@jrmerz I just saw this issue while looking at past issues. Not, sure if it is still an issue. Yes, that's correct. Those time-series net evaporation rate time-series (Evaporation - Precipitation). So, some winter months, if precipitation on reservoir area is greater than evaporation, then it is negative.

**Comment by jrmerz** [comment]
@msdogan Thanks!
