### ISSUE TITLE
Missing EAC data in S09I05  PRI files

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-data#54]
In attempting to recreate the current Calvind s09I05 runs, I noticed that there are no EAC (Elevation Area Capacity) input lines in the S09I05.pri file.  Is that correct?

**Comment by msdogan** [comment]
Yes, those inputs are not used by HEC-PRM. But, we will keep them, as we discussed in the meeting, since others might be interested in seeing EAC curves.
