### ISSUE TITLE
Small but import changes in Penalty functions

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-data#55]
@msdogan this I guess is not an error, but just something I noticed.  Originally, when converting to and from the DSS PD files, I used 3 decimal points as a roundoff.  I mistakenly thought that would be reasonable.  However, this causes errors when running the hecprm.exe code.  This is because in penalty functions, the x value needs to change, and some changes are very small, for example that of node HXI201-EXT_YUBA Flow penalty functions.

![image](https://cloud.githubusercontent.com/assets/344953/11199971/10dba99c-8c87-11e5-8f91-2918e61206d1.png)

**Comment by msdogan** [comment]
I this issue was also resolved. We will use 7 decimal points and/or modify penalty data.
