### ISSUE TITLE
Add docson support for calvin-network-data

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-data#6]
Currently, I am copying the JSON-SCHEMA files to cwn.casil.ucdavis.edu in order to get the online viewing of the json schema via docson.  eg:
http://watershed.ice.ucdavis.edu/docson/#http://watershed.ice.ucdavis.edu/json-schema/types.json
http://watershed.ice.ucdavis.edu/docson/#http://watershed.ice.ucdavis.edu/json-schema/node.json

What would be better is for something like 

``` bash
grunt serve
```

To include that service.  Again, I think this is part of calvin-network-data, (Via an NPM Install? ) , but reasonable people disagree.

**Comment by jrmerz** [comment]
I have added a bower init file that will install docson via bower.  Then to serve from apache is simple:
- cloned repo to /opt/github/calvin-network-data
- cd /opt/github/calvin-network-data && bower install
- linked /var/www/docson -> /opt/github/calvin-network-data/bower_components/docson
- linked /var/www/json-schema -> /opt/github/calvin-network-data/json-schema

I can add a little express server & grunt to the repo, but seems like overkill to me... IMHO.
