### ISSUE TITLE
Remove Binary history

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-data#60]
We have split off the binary data from the data repo.  I think now is a good time to clean up the history of the repo as well.  I have done the following commands: 

``` bash
git branch S09I05 $(echo "Initial S09I05 Verion" | git commit-tree HEAD^{tree})
git push origin S09I05
git branch -m master with-binary
git push origin with-binary
```

The S09I05 branch now has one commit, and the with-binary has all the 143  (mostly binary) commits.  The master branch has all commits as well.  I propose we replace the master with the S09I05 branch, with 

``` bash
git push origin --delete master
git branch -m S09I05 master
git push origin master
```

The I guess partly scary part being the deletion of master, which still should be in the `with-binary`  release, I believe.  That will leave us with three repos: master=S09I05 (but not following each other) and the with-binary for later deletion.  So after the above, I suppose we could do

``` bash
git push origin --delete S09I05
git checkout master
git checkout -b S09I05
git push --set-upstream origin S09I05
```

So they track.

Used info from:
- [Initial Commit](http://stackoverflow.com/questions/9683279/make-the-current-commit-the-only-initial-commit-in-a-git-repository)
- [Rename Remote on Github](http://blog.changecong.com/2012/10/rename-a-remote-branch-on-github/)
  Sound correct?

**Comment by jrmerz** [comment]
@qjhart you ran this, no?
