### ISSUE TITLE
Missing Link Cost (Penalties) on PMP links

### ISSUE THREAD

**Issue by msdogan** [ucd-cws/calvin-network-data#63]
@qjhart @jrmerz I opened the same issue under HOBBEStoPRM repo (https://github.com/msdogan/HOBBEStoPRMcomparison/issues/4), but I guess this is a better place. We discovered that cost values are missing for following pumping plant links:

```
PMP-DOS AMIGOS_D744A
PMP-ONEIL_D814
PMP-WHEELERRIDGE_D862A
PMP-OSO_D884
PMP-SOUTHBAY_D891
PMP-DEL VALLE_SR-DLV
PMP-GIANELLI_SR-SNL
PMP-CONTRA COSTA 1_C70
PMP-BANKS_D800
PMP-TRACY_D701
PMP-BADGER HILL_D847
PMP-LASPERILLAS_PMP-BADGERHILL
PMP-BUENAVISTA_D860
PMP-EDMONSTON_C103
PMP-PEARBLOSSOM_C124
PMP-CHRISMAN_D862B
```

They all have piecewise cost curve penalties (PQ). The missing cost curves could be because of Microsoft Access Database. So, I made some changes to that for those links.
- Updated month information
- Updated link label

Hopefully with those changes, your script can read from updated `S09I05.mdb`, which is attached here and write cost values to `.pri` for those links.

[S09I05.zip](https://github.com/ucd-cws/calvin-network-data/files/372458/S09I05.zip)

**Comment by jrmerz** [comment]
We should probably be making all changes to data repository (https://github.com/ucd-cws/calvin-network-data).  That's our 'database'.  Unfortunately we would have to wait to script those changes as I do not have a Access DB license.

If you are able to pull out the data, in say, csv format, you or I could manually update.

Just a reminder, the app (https://cwn.casil.ucdavis.edu/#info/PMP_ONeill-D814) has 'Download data file excel' button.  This will download a specially formatted Excel file that can be used to make modifications to the data repo via to cnf tool's excel command.

``` bash
cnf excel -x /path/to/PMP_ONeill-D814.xls
```

Now this command is a little difficult to use to add data, cause you need to understand the header line as well as manually modify the GeoJSON for the node/link.   Its primary purpose is easier data edits.

**Comment by msdogan** [comment]
@jrmerz I thought you and Quinn have a script that can read Microsoft Access DB file. But, I think I can manually add cost data to those pumping links. Yes, I can pull the data from DSS file in CSV format. I guess I need to add cost folder that contains penalty values for each month in csv format, and then I will update link.geojson file. I will send a pull request when I am done with that.

**Comment by jrmerz** [comment]
Ya, I think quinn has that magic script.  But for now the edit and pull request sounds great!  That's actually how we would like to see outside modifications made in the future, once we are rolling.
