### ISSUE TITLE
Fix JSON-SCHEMA references for docson

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-data#7]
While the JSON-SCHEMA naming seems okay for ts4, it seems goofy for the docson tool.  At least the references are not included in the docs.  Can we figure out why that is?

**Comment by jrmerz** [comment]
@qjhart add links for tools

**Comment by qjhart** [comment]
Docson is currently running on watershed.ice.ucdavis.edu /var/www/html/docson, eg:
http://watershed.ice.ucdavis.edu/docson/#http://watershed.ice.ucdavis.edu/json-schema/node.json
http://watershed.ice.ucdavis.edu/docson/#http://watershed.ice.ucdavis.edu/json-schema/types.json

Docson is at:  https://github.com/lbovet/docson
I don't think you can do npm install docson, but I could be wrong.

**Comment by jrmerz** [comment]
No, but it's in bower :) https://github.com/lbovet/docson/blob/master/bower.json

**Comment by jrmerz** [comment]
Per issue #6 docson is now part of the data repo via bower.

@qjhart can you add a little more detail about the parsing issue, and I will look to track down.
